### ISSUE TITLE
EntityWhereCondition<T> : A parameter named @Date already exits / Can't apply two operators on the same parameter

### ISSUE THREAD

**Issue by fperreaultnv** [julienblin/uno-serverless#30] opened 2018-07-23 14:36 UTC
I have the following code : 

`query`
`        .where<PineappleEvent>({ date: [eventFilters.from, Operator.Gte] })`
`        .where<PineappleEvent>({ date: [eventFilters.to, Operator.Lte]});`

When executed, I receive the following exception : 

{
  "context": {
    "invocationId": "cce0b2a2-497d-4769-aaff-c6210310d732",
    "original": {
      "invocationId": "cce0b2a2-497d-4769-aaff-c6210310d732",
      "executionContext": {
        "invocationId": "cce0b2a2-497d-4769-aaff-c6210310d732",
        "functionName": "events",
        "functionDirectory": "C:\\Src\\pineapple\\api\\dist\\events"
      },
      "bindings": {
        "req": {
          "method": "GET",
          "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
          "originalUrl": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
          "headers": {
            "connection": "keep-alive",
            "content-type": "application/json",
            "accept": "*/*",
            "accept-encoding": "gzip, deflate",
            "host": "localhost:7071",
            "user-agent": "PostmanRuntime/7.1.5"
          },
          "query": {
            "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
            "from": "1532013777213",
            "to": "1532113777213"
          },
          "params": {}
        }
      },
      "bindingData": {
        "invocationId": "cce0b2a2-497d-4769-aaff-c6210310d732",
        "$request": {
          "http": {
            "headers": {
              "connection": "keep-alive",
              "content-type": "application/json",
              "accept": "*/*",
              "accept-encoding": "gzip, deflate",
              "host": "localhost:7071",
              "user-agent": "PostmanRuntime/7.1.5"
            },
            "params": {},
            "query": {
              "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
              "from": "1532013777213",
              "to": "1532113777213"
            },
            "method": "GET",
            "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
            "body": null,
            "statusCode": "",
            "enableContentNegotiation": false,
            "rawBody": null
          },
          "data": "http"
        },
        "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
        "from": 1532013777213,
        "to": 1532113777213,
        "query": {
          "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
          "from": "1532013777213",
          "to": "1532113777213"
        },
        "headers": {
          "connection": "keep-alive",
          "content-Type": "application/json",
          "accept": "*/*",
          "accept-Encoding": "gzip, deflate",
          "host": "localhost:7071",
          "user-Agent": "PostmanRuntime/7.1.5"
        },
        "req": {
          "http": {
            "headers": {
              "connection": "keep-alive",
              "content-type": "application/json",
              "accept": "*/*",
              "accept-encoding": "gzip, deflate",
              "host": "localhost:7071",
              "user-agent": "PostmanRuntime/7.1.5"
            },
            "params": {},
            "query": {
              "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
              "from": "1532013777213",
              "to": "1532113777213"
            },
            "method": "GET",
            "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
            "body": null,
            "statusCode": "",
            "enableContentNegotiation": false,
            "rawBody": null
          },
          "data": "http"
        },
        "sys": {
          "methodName": "events",
          "utcNow": "2018-07-23T14:30:24.1624764Z",
          "randGuid": "f0669f42-37a3-4687-b0f1-7e98b6e25a89"
        }
      },
      "req": {
        "method": "GET",
        "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
        "originalUrl": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
        "headers": {
          "connection": "keep-alive",
          "content-type": "application/json",
          "accept": "*/*",
          "accept-encoding": "gzip, deflate",
          "host": "localhost:7071",
          "user-agent": "PostmanRuntime/7.1.5"
        },
        "query": {
          "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
          "from": "1532013777213",
          "to": "1532113777213"
        },
        "params": {}
      },
      "res": {
        "headers": {},
        "_done": "******"
      }
    },
    "provider": "AzureFunctions"
  },
  "error": {
    "message": "A parameter named @date already exits. (for Thu Jul 19 2018 11:22:57 GMT-0400 (Eastern Daylight Time), Fri Jul 20 2018 15:09:37 GMT-0400 (Eastern Daylight Time))"
  },
  "errorStackTrace": "Error: A parameter named @date already exits. (for Thu Jul 19 2018 11:22:57 GMT-0400 (Eastern Daylight Time), Fri Jul 20 2018 15:09:37 GMT-0400 (Eastern Daylight Time))\n    at string.Object.entries.forEach.t (webpack-internal:///./node_modules/uno-serverless-azure/dist/index.js:1:2013)\n    at Array.forEach (<anonymous>)\n    at Object.where (webpack-internal:///./node_modules/uno-serverless-azure/dist/index.js:1:1951)\n    at string.Object.entries.forEach.t (webpack-internal:///./node_modules/uno-serverless-azure/dist/index.js:1:2280)\n    at Array.forEach (<anonymous>)\n    at Object.where (webpack-internal:///./node_modules/uno-serverless-azure/dist/index.js:1:2158)\n    at DocumentDbEventService.getFilteredEvents (webpack-internal:///./src/services/event.service.ts:76:14)\n    at DocumentDbEventService.getEvents (webpack-internal:///./src/services/event.service.ts:11:31)\n    at exports.handler._common_1.httpFunc.use.handler.uno_serverless_1.http (webpack-internal:///./src/handlers/events.ts:53:41)\n    at s (webpack-internal:///./node_modules/uno-serverless/dist/index.js:24:19770)",
  "event": {
    "headers": {
      "connection": "keep-alive",
      "content-type": "application/json",
      "accept": "*/*",
      "accept-encoding": "gzip, deflate",
      "host": "localhost:7071",
      "user-agent": "PostmanRuntime/7.1.5"
    },
    "httpMethod": "get",
    "original": {
      "method": "GET",
      "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
      "originalUrl": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213",
      "headers": {
        "connection": "keep-alive",
        "content-type": "application/json",
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "host": "localhost:7071",
        "user-agent": "PostmanRuntime/7.1.5"
      },
      "query": {
        "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
        "from": "1532013777213",
        "to": "1532113777213"
      },
      "params": {}
    },
    "parameters": {
      "categoryIds": "1IHaN2y4YwigCWCsOY2yi4",
      "from": "1532013777213",
      "to": "1532113777213"
    },
    "unoEventType": "http",
    "url": "http://localhost:7071/api/events?categoryIds=1IHaN2y4YwigCWCsOY2yi4&from=1532013777213&to=1532113777213"
  }
}

**Comment by julienblin** [comment] 2018-07-23 15:15
Duplicate of #29

**Closed by julienblin** 2018-07-23 15:15 UTC
